[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "temenosCloudSystemControlServiceElasticity"
version = "0.1.0"
license = ["Apache-2.0"]
authors = ["iamSahdoon"]
keywords = ["banking", "temenos", "api", "cloud", "system", "control", "service", "elasticity"]
repository = "https://github.com/iamSahdoon/module-ballerinax-temenosCloudSystemControlServiceElasticity"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
